In [9]:
import numpy as np

def vanderFunc(arr, N=None, increasing=False):
    if not N:
        N = len(arr)
    return np.vander(np.array(arr),N,increasing=increasing)    


print(vanderFunc([1,2,3,4,5]))

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [17]:
def movingAvg(arr, k):
    values = np.array(arr)
    num = len(values) - k + 1
    movingAvgs = []
    
    for i in range(num):
        avg = np.mean(values[i:i+k])
        movingAvgs.append(avg)
        
    return movingAvgs
        
print(movingAvg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], 3))

[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
